### ISSUE TITLE
Plugin completely broken - Overhead attack timer countdown resets/bugs out at 3

### ISSUE THREAD

**Issue by DangersClose** [ngraves95/attacktimer#23] opened 2023-10-14 04:52 UTC
Please fix plugin it is great.

**Comment by ozohead** [comment] 2023-11-01 17:25
Same with me have you found any solution?

**Comment by ngraves95** [comment] 2023-12-27 20:37
Can you include some screenshots or gifs of what is happening? Please include other information like:
* the weapon.
* the attack style.
* a screenshot of your attacktimer config settings.

**Comment by ngraves95** [comment] 2023-12-27 21:10
Sounds like a duplicate of https://github.com/ngraves95/attacktimer/issues/26. Closing until this can be reproed

**Closed by ngraves95** 2023-12-27 21:10 UTC
