### ISSUE TITLE
Timer keeps reseting / losing track of ticks

### ISSUE THREAD

**Issue by Matt89aa** [ngraves95/attacktimer#22] opened 2023-10-13 23:13 UTC
I just installed the most recent windows updates which may be linked to this - issue did not exist before. Seems to happen on all weapons

**Comment by DangersClose** [comment] 2023-10-14 04:43
Yes i am having this exact same issue. Good to see it is just not me because i have tried everything to fix.

Overhead attack timer countdown goes like 5,4,3 and then disapears at 3.

Only weapon it still works for is whip but everything else seems broken.

Hopefully this can get fixed somehow because i love this plugin!

**Comment by ozohead** [comment] 2023-11-01 17:26
any solution matt?

**Comment by ngraves95** [comment] 2023-12-27 21:09
Sounds like a duplicate of https://github.com/ngraves95/attacktimer/issues/26. I'm going to close until someone reports this getting repro-ed.

**Closed by ngraves95** 2023-12-27 21:09 UTC
